# Generated by Django 4.2.1 on 2023-06-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JbDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1000)),
                ('scraped_date', models.CharField(max_length=1000)),
                ('job_image', models.CharField(max_length=1000)),
            ],
        ),
    ]
